### ISSUE TITLE
Broken spec?

### ISSUE THREAD

**Issue by pedrorgirardi** [riverford/compound#1]
Hi, making this call with Orchestra instrumentation turned on throws the error:

```Clojure
(c/compound {:primary-index-def {:key :id} :secondary-index-defs [{:key :colour}]})
```

![screen shot 2017-12-20 at 11 24 31](https://user-images.githubusercontent.com/585191/34209226-765f417e-e578-11e7-8cea-b28af6ff91b6.png)

Am I missing something? And thanks for **compound**. 👍

**Comment by danielneal** [comment]
Good catch, thanks! 
There's probably a bunch more like this, as I haven't been using orchestra to check return specs. I'll use orchestra to run the tests and see what else turns up.

**Comment by pedrorgirardi** [comment]
Cool! Thanks @danielneal

**Comment by danielneal** [comment]
I've pulled in orchestra and rerun the tests - turns out the missing spec you found was the only one, but it was called from a whole bunch of places so good to sort it out. Thanks!

**Comment by pedrorgirardi** [comment]
That's nice! Thanks for being so quick to fix & release it.
